/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1XWyRcacryEyco6uPV1CR
// Component: LxRLO8beitYM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: lKu0B9xgLMgZ/component
import Button from "../../Button"; // plasmic-import: vFerdvZMwcM9/component
import Footer from "../../Footer"; // plasmic-import: U1-LJF1kZHcJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectcss
import sty from "./PlasmicContactUs.module.css"; // plasmic-import: LxRLO8beitYM/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 57zAO7P9sacL/icon
import LoactionVectorSvgIcon from "./icons/PlasmicIcon__LoactionVectorSvg"; // plasmic-import: CRzn_nzFeoRk/icon
import PhoneVectorSvgIcon from "./icons/PlasmicIcon__PhoneVectorSvg"; // plasmic-import: KWkePGqocTiV/icon
import EmailVectorSvgIcon from "./icons/PlasmicIcon__EmailVectorSvg"; // plasmic-import: NkHc1EuLzV0x/icon

createPlasmicElementProxy;

export type PlasmicContactUs__VariantMembers = {};
export type PlasmicContactUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactUs__VariantsArgs;
export const PlasmicContactUs__VariantProps = new Array<VariantPropType>();

export type PlasmicContactUs__ArgsType = {};
type ArgPropType = keyof PlasmicContactUs__ArgsType;
export const PlasmicContactUs__ArgProps = new Array<ArgPropType>();

export type PlasmicContactUs__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  pageBanerSection?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  formContainer2?: Flex__<"div">;
  textarea?: Flex__<"textarea">;
  button?: Flex__<typeof Button>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultContactUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactUs__RenderFunc(props: {
  variants: PlasmicContactUs__VariantsArgs;
  args: PlasmicContactUs__ArgsType;
  overrides: PlasmicContactUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__qoY1R)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__aDbJh
                )}
              >
                {"Contact Us"}
              </h1>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__dXgY)}>
            <div className={classNames(projectcss.all, sty.freeBox__vU)}>
              <div className={classNames(projectcss.all, sty.freeBox___7MbZ)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2YekT)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__axd3I)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__wg0Iz)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/professional_services/images/globeTrotter18280791920Jpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__nOjP2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dL1VQ
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__yLNgz
                          )}
                        >
                          {"Get In touch"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bjhat
                          )}
                        >
                          {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                          }
                        </div>
                        <div
                          data-plasmic-name={"formContainer2"}
                          data-plasmic-override={overrides.formContainer2}
                          className={classNames(
                            projectcss.all,
                            sty.formContainer2
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.columns__tJxfN
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__ys6E8
                              )}
                            >
                              <input
                                className={classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.textInput__yo02D
                                )}
                                placeholder={"First name"}
                                size={1}
                                type={"text"}
                                value={""}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__bvZrZ
                              )}
                            >
                              <input
                                className={classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.textInput__emFd
                                )}
                                placeholder={"Last name"}
                                size={1}
                                type={"text"}
                                value={""}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__isDWr
                              )}
                            >
                              <input
                                className={classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.textInput__h0RZs
                                )}
                                placeholder={"Email address"}
                                size={1}
                                type={"text"}
                                value={""}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__r3SIm
                              )}
                            >
                              <input
                                className={classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.textInput___8Jwge
                                )}
                                placeholder={"Phone number"}
                                size={1}
                                type={"text"}
                                value={""}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.columns__buebv
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__enyd7
                              )}
                            >
                              <input
                                className={classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.textInput__fgEt
                                )}
                                placeholder={"Company"}
                                size={1}
                                type={"text"}
                                value={""}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column___9O937
                              )}
                            >
                              <textarea
                                data-plasmic-name={"textarea"}
                                data-plasmic-override={overrides.textarea}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.textarea,
                                  sty.textarea
                                )}
                                placeholder={"Message"}
                                value={""}
                              />

                              <Button
                                data-plasmic-name={"button"}
                                data-plasmic-override={overrides.button}
                                className={classNames(
                                  "__wab_instance",
                                  sty.button
                                )}
                                color={"blackCoffee"}
                                submitsForm={true}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__cnmok
                                  )}
                                >
                                  {"Send Message"}
                                </div>
                              </Button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__f4Sht)}>
            <div className={classNames(projectcss.all, sty.freeBox___8USL)}>
              <div className={classNames(projectcss.all, sty.freeBox__y0Wwu)}>
                <div className={classNames(projectcss.all, sty.freeBox__qV9E)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__i4W7W)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__w6B5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__b11Mi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__frUgp
                          )}
                        >
                          <LoactionVectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sS1W3
                            )}
                            role={"img"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kn3T
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__x2Rp
                            )}
                          >
                            {"Address"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aPkb
                            )}
                          >
                            {"121 state lorem state"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__oUdIo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wzGyM
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bpwcG
                          )}
                        >
                          <PhoneVectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rqjip
                            )}
                            role={"img"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cXhRg
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___1TB9B
                            )}
                          >
                            {"Phone"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fks8N
                            )}
                          >
                            {"888888885588"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__cOmU)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kJbdz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vygsJ
                          )}
                        >
                          <EmailVectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___34H3A
                            )}
                            role={"img"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fDzLc
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__kheAg
                            )}
                          >
                            {"Email"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__arxiy
                            )}
                          >
                            {"Info@gmail.com"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "img",
    "formContainer2",
    "textarea",
    "button",
    "footer"
  ],
  header: ["header"],
  pageBanerSection: ["pageBanerSection"],
  img: ["img"],
  formContainer2: ["formContainer2", "textarea", "button"],
  textarea: ["textarea"],
  button: ["button"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageBanerSection: "div";
  img: typeof PlasmicImg__;
  formContainer2: "div";
  textarea: "textarea";
  button: typeof Button;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactUs__VariantsArgs;
    args?: PlasmicContactUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContactUs__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContactUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactUs__ArgProps,
          internalVariantPropNames: PlasmicContactUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactUs";
  } else {
    func.displayName = `PlasmicContactUs.${nodeName}`;
  }
  return func;
}

export const PlasmicContactUs = Object.assign(
  // Top-level PlasmicContactUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    img: makeNodeComponent("img"),
    formContainer2: makeNodeComponent("formContainer2"),
    textarea: makeNodeComponent("textarea"),
    button: makeNodeComponent("button"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicContactUs
    internalVariantProps: PlasmicContactUs__VariantProps,
    internalArgProps: PlasmicContactUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicContactUs;
/* prettier-ignore-end */
