/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1XWyRcacryEyco6uPV1CR
// Component: bJFQWGdGnDO3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: lKu0B9xgLMgZ/component
import ServicesWhite from "../../ServicesWhite"; // plasmic-import: JZUuLltS-WiV/component
import Footer from "../../Footer"; // plasmic-import: U1-LJF1kZHcJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: bJFQWGdGnDO3/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: QPUNRn_j-mSY/icon

createPlasmicElementProxy;

export type PlasmicServices__VariantMembers = {};
export type PlasmicServices__VariantsArgs = {};
type VariantPropType = keyof PlasmicServices__VariantsArgs;
export const PlasmicServices__VariantProps = new Array<VariantPropType>();

export type PlasmicServices__ArgsType = {};
type ArgPropType = keyof PlasmicServices__ArgsType;
export const PlasmicServices__ArgProps = new Array<ArgPropType>();

export type PlasmicServices__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  pageBanerSection?: Flex__<"div">;
  h1?: Flex__<"h1">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultServicesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicServices__RenderFunc(props: {
  variants: PlasmicServices__VariantsArgs;
  args: PlasmicServices__ArgsType;
  overrides: PlasmicServices__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__my1Q)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Services"}
              </h1>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__w5Xn7)}>
            <div className={classNames(projectcss.all, sty.freeBox__dooVw)}>
              <div className={classNames(projectcss.all, sty.freeBox___5VVd)}>
                <div className={classNames(projectcss.all, sty.freeBox__moeI3)}>
                  <div
                    className={classNames(projectcss.all, sty.columns___8Nqqh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___7PcBh)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__aqBdP
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___83ESg
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hdwVn)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__nb9QE
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__pfupS
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___6UmAw)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__xgoS3
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__fk8Lw
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qbiPd)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__m17E
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__yKn9H
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___1Luw0)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__r7Hno
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__bzDPo
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__yUv8K)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite___57AjF
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__sj8JA
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__cdrkB)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__evzHx
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "Why Choose Us"
                : "Our process"}
            </h2>
            <div className={classNames(projectcss.all, sty.freeBox___5ZJ5X)}>
              <div className={classNames(projectcss.all, sty.columns__qQO)}>
                <div className={classNames(projectcss.all, sty.column__lDAef)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__xfBm
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__id5Oz
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__j6Vdm)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite___6Hmvi
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ptjpw
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ct7AO)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__okV1K
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ct3YG
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__sHwd)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__jsExr
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__sdnVw
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__f21Gf)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__rCvJ3
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___6GFlG
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__f9Dq3)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__jmfne
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___2J9Xk
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__hyPpc)}>
            <div className={classNames(projectcss.all, sty.freeBox__rwojU)}>
              <div className={classNames(projectcss.all, sty.freeBox___0D8Ht)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6AfpB)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__hSKb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__nytY4)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__dIiYr
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__fdbZ
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___6C2F)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__seExn
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__gmIm
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ntjRh)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__y8HbX
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__mJaQr
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__c0Kly)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__nneXm
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__tdmWt
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__zvADw)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__kLa9
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___3Ghu
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___7XDCe)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__oxHkX
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__osplX
                            )}
                          >
                            {"Services main"}
                          </h3>
                        }
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__qbLR)}>
            <div className={classNames(projectcss.all, sty.freeBox__mNix7)}>
              <div className={classNames(projectcss.all, sty.freeBox___1DbIy)}>
                <div className={classNames(projectcss.all, sty.freeBox__qM5L)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__bh6CS)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__km8Ei)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/professional_services/images/woman32879561920Jpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__vOsk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rJJkO
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__jvWl3
                          )}
                        >
                          {"Why Choose Us"}
                        </h2>
                        <div
                          data-plasmic-name={"text"}
                          data-plasmic-override={overrides.text}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text
                          )}
                        >
                          {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns___5Tw8Q
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__mAQrI
                            )}
                          >
                            <ServicesWhite
                              className={classNames(
                                "__wab_instance",
                                sty.servicesWhite__jG6My
                              )}
                              slot={
                                <h3
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h3,
                                    projectcss.__wab_text,
                                    sty.h3___45Bse
                                  )}
                                >
                                  {"Services main"}
                                </h3>
                              }
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__kFIp
                            )}
                          >
                            <ServicesWhite
                              className={classNames(
                                "__wab_instance",
                                sty.servicesWhite__eoxk
                              )}
                              slot={
                                <h3
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h3,
                                    projectcss.__wab_text,
                                    sty.h3__hvPm3
                                  )}
                                >
                                  {"Services main"}
                                </h3>
                              }
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column___6MIr
                            )}
                          >
                            <ServicesWhite
                              className={classNames(
                                "__wab_instance",
                                sty.servicesWhite__hNuk
                              )}
                              slot={
                                <h3
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h3,
                                    projectcss.__wab_text,
                                    sty.h3__gJNi
                                  )}
                                >
                                  {"Services main"}
                                </h3>
                              }
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__zMq9M
                            )}
                          >
                            <ServicesWhite
                              className={classNames(
                                "__wab_instance",
                                sty.servicesWhite__dFv3K
                              )}
                              slot={
                                <h3
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h3,
                                    projectcss.__wab_text,
                                    sty.h3___2GoLi
                                  )}
                                >
                                  {"Services main"}
                                </h3>
                              }
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanerSection", "h1", "img", "text", "footer"],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  img: ["img"],
  text: ["text"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageBanerSection: "div";
  h1: "h1";
  img: typeof PlasmicImg__;
  text: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicServices__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicServices__VariantsArgs;
    args?: PlasmicServices__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicServices__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicServices__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
