/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1XWyRcacryEyco6uPV1CR
// Component: bJFQWGdGnDO3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: lKu0B9xgLMgZ/component
import { AntdPopover } from "@plasmicpkgs/antd5/skinny/registerPopover";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: bJFQWGdGnDO3/css

import Asset1Svg2Icon from "./icons/PlasmicIcon__Asset1Svg2"; // plasmic-import: OyrJi1cbWLm4/icon
import Asset3SvgIcon from "./icons/PlasmicIcon__Asset3Svg"; // plasmic-import: ia1FitBk10_u/icon

createPlasmicElementProxy;

export type PlasmicServices__VariantMembers = {};
export type PlasmicServices__VariantsArgs = {};
type VariantPropType = keyof PlasmicServices__VariantsArgs;
export const PlasmicServices__VariantProps = new Array<VariantPropType>();

export type PlasmicServices__ArgsType = {};
type ArgPropType = keyof PlasmicServices__ArgsType;
export const PlasmicServices__ArgProps = new Array<ArgPropType>();

export type PlasmicServices__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  pageBanerSection?: Flex__<"div">;
  h1?: Flex__<"h1">;
  columns?: Flex__<"div">;
  multilimpador?: Flex__<typeof AntdPopover>;
  descricaoMulti?: Flex__<"div">;
  porcelato?: Flex__<typeof AntdPopover>;
  descricaoMulti2?: Flex__<"div">;
  porcelatoPesada?: Flex__<typeof AntdPopover>;
  descricaoMulti3?: Flex__<"div">;
};

export interface DefaultServicesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicServices__RenderFunc(props: {
  variants: PlasmicServices__VariantsArgs;
  args: PlasmicServices__ArgsType;
  overrides: PlasmicServices__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "multilimpador.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "porcelato.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "porcelatoPesada.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__my1Q)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Nossos produtos"}
              </h1>
            </div>
          </div>
          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column__dJj6G)}>
              <AntdPopover
                data-plasmic-name={"multilimpador"}
                data-plasmic-override={overrides.multilimpador}
                arrow={true}
                className={classNames("__wab_instance", sty.multilimpador)}
                content={
                  <div
                    data-plasmic-name={"descricaoMulti"}
                    data-plasmic-override={overrides.descricaoMulti}
                    className={classNames(projectcss.all, sty.descricaoMulti)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__nIsVl)}
                      displayHeight={"277px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"381%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"548px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/professional_services/images/capaPng2.png",
                        fullWidth: 2182,
                        fullHeight: 1937,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pGxbM
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__rJhs
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#028C1B" }}
                              >
                                {"Pioneer Multilimpador"}
                              </span>
                            </React.Fragment>
                          </h3>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2XkR6
                      )}
                    >
                      {
                        "Indicado para limpeza por pulveriza\u00e7\u00e3o, com ou sem enx\u00e1gue, em diversas superf\u00edcies, como paredes, revestimentos, f\u00f3rmicas, chapas, fog\u00f5es, geladeiras, macas, pisos vitrificados, cer\u00e2micas, m\u00e1rmores, granitos, porcelanatos, pisos vin\u00edlicos, paviflex, estofados, carpetes, couros, pl\u00e1sticos, borrachas, acr\u00edlicos, policarbonatos e superf\u00edcies lav\u00e1veis em geral."
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xgtS
                      )}
                    >
                      {"Dilui\u00e7\u00e3o"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__en7HP
                      )}
                    >
                      {
                        "\u2022 Limpeza pesada: 1:5 a 1:10\n\u2022 Limpeza de manuten\u00e7\u00e3o: 1:10 a 1:20"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fvKZu
                      )}
                    >
                      {"Embalagens Dispon\u00edveis"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kGpdT)}
                    >
                      <Asset1Svg2Icon
                        className={classNames(projectcss.all, sty.svg__bfYi6)}
                        role={"img"}
                      />

                      <Asset3SvgIcon
                        className={classNames(projectcss.all, sty.svg___16Xrk)}
                        role={"img"}
                      />
                    </div>
                  </div>
                }
                contentText={(() => {
                  try {
                    return undefined;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "sdvsd";
                    }
                    throw e;
                  }
                })()}
                defaultOpen={false}
                defaultStylesClassName={classNames(
                  projectcss.root_reset,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  styleTokensClassNames
                )}
                mouseEnterDelay={0}
                mouseLeaveDelay={0}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "multilimpador",
                    "open"
                  ]).apply(null, eventArgs);
                }}
                open={generateStateValueProp($state, ["multilimpador", "open"])}
                popoverScopeClassName={sty["multilimpador__popover"]}
                title={null}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rmWoj)}
                  displayHeight={"277px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"381%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"548px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/professional_services/images/capaPng2.png",
                    fullWidth: 2182,
                    fullHeight: 1937,
                    aspectRatio: undefined
                  }}
                />
              </AntdPopover>
            </div>
            <div className={classNames(projectcss.all, sty.column__cSkl8)}>
              <AntdPopover
                data-plasmic-name={"porcelato"}
                data-plasmic-override={overrides.porcelato}
                arrow={true}
                className={classNames("__wab_instance", sty.porcelato)}
                content={
                  <div
                    data-plasmic-name={"descricaoMulti2"}
                    data-plasmic-override={overrides.descricaoMulti2}
                    className={classNames(projectcss.all, sty.descricaoMulti2)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__uHkJp)}
                      displayHeight={"277px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"381%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"548px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/professional_services/images/porcelatoCapaPng.png",
                        fullWidth: 2182,
                        fullHeight: 1937,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ymTGr
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__seLhc
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#028C1B" }}
                              >
                                {"Pioneer Porcelato Manuten\u00e7\u00e3o"}
                              </span>
                            </React.Fragment>
                          </h3>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6UmP
                      )}
                    >
                      {
                        "Produto concentrado indicado para limpeza e manuten\u00e7\u00e3o di\u00e1ria de porcelanatos, granitos, m\u00e1rmores e pisos nobres em geral. Proporciona brilho e fragr\u00e2ncia agrad\u00e1vel, sem agredir as superf\u00edcies."
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__izfiO
                      )}
                    >
                      {"Dilui\u00e7\u00e3o"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6PaR
                      )}
                    >
                      {
                        "\u2022 1:50\nCada litro do produto dilu\u00eddo rende aproximadamente 5 a 10 m\u00b2, conforme as condi\u00e7\u00f5es do piso."
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0WpQ9
                      )}
                    >
                      {"Embalagens Dispon\u00edveis"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ot9T6)}
                    >
                      <Asset1Svg2Icon
                        className={classNames(projectcss.all, sty.svg__uu7OF)}
                        role={"img"}
                      />

                      <Asset3SvgIcon
                        className={classNames(projectcss.all, sty.svg__hqdhY)}
                        role={"img"}
                      />
                    </div>
                  </div>
                }
                contentText={(() => {
                  try {
                    return undefined;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "sdvsd";
                    }
                    throw e;
                  }
                })()}
                defaultOpen={false}
                defaultStylesClassName={classNames(
                  projectcss.root_reset,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  styleTokensClassNames
                )}
                mouseEnterDelay={0}
                mouseLeaveDelay={0}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "porcelato",
                    "open"
                  ]).apply(null, eventArgs);
                }}
                open={generateStateValueProp($state, ["porcelato", "open"])}
                popoverScopeClassName={sty["porcelato__popover"]}
                title={null}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1BDsz)}
                  displayHeight={"277px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"381%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"548px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/professional_services/images/porcelatoCapaPng.png",
                    fullWidth: 2182,
                    fullHeight: 1937,
                    aspectRatio: undefined
                  }}
                />
              </AntdPopover>
            </div>
            <div className={classNames(projectcss.all, sty.column__sjyhC)}>
              <AntdPopover
                data-plasmic-name={"porcelatoPesada"}
                data-plasmic-override={overrides.porcelatoPesada}
                arrow={true}
                className={classNames("__wab_instance", sty.porcelatoPesada)}
                content={
                  <div
                    data-plasmic-name={"descricaoMulti3"}
                    data-plasmic-override={overrides.descricaoMulti3}
                    className={classNames(projectcss.all, sty.descricaoMulti3)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jnLj)}
                      displayHeight={"277px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"381%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"548px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/professional_services/images/porcelatoPesadaCapaPng.png",
                        fullWidth: 2182,
                        fullHeight: 1937,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lu05V
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__ujWo
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#028C1B" }}
                              >
                                {"Pioneer Porcelato Limpeza Pesada"}
                              </span>
                            </React.Fragment>
                          </h3>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l953
                      )}
                    >
                      {
                        "Produto concentrado de alta performance, indicado para limpeza pesada e desincrusta\u00e7\u00e3o de porcelanatos em geral. Remove sujeiras dif\u00edceis, encardidos e manchas, auxiliando no clareamento de rejuntes sem agredir a superf\u00edcie quando utilizado conforme a dilui\u00e7\u00e3o recomendada."
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rFeul
                      )}
                    >
                      {"Dilui\u00e7\u00e3o"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dn9XG
                      )}
                    >
                      {
                        "\u2022 1:5 a 1:10\nIndica\u00e7\u00e3o:\n\u2022 Porcelanatos encardidos e manchados\n\u2022 Limpeza pesada e desincrusta\u00e7\u00e3o\n\u2022 Clareamento de rejuntes"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vF4
                      )}
                    >
                      {"Embalagens Dispon\u00edveis"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wrTC)}
                    >
                      <Asset1Svg2Icon
                        className={classNames(projectcss.all, sty.svg__ux50E)}
                        role={"img"}
                      />

                      <Asset3SvgIcon
                        className={classNames(projectcss.all, sty.svg__jDabg)}
                        role={"img"}
                      />
                    </div>
                  </div>
                }
                contentText={(() => {
                  try {
                    return undefined;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "sdvsd";
                    }
                    throw e;
                  }
                })()}
                defaultOpen={false}
                defaultStylesClassName={classNames(
                  projectcss.root_reset,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  styleTokensClassNames
                )}
                mouseEnterDelay={0}
                mouseLeaveDelay={0}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "porcelatoPesada",
                    "open"
                  ]).apply(null, eventArgs);
                }}
                open={generateStateValueProp($state, [
                  "porcelatoPesada",
                  "open"
                ])}
                popoverScopeClassName={sty["porcelatoPesada__popover"]}
                title={null}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__q3SeX)}
                  displayHeight={"277px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"381%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"548px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/professional_services/images/porcelatoPesadaCapaPng.png",
                    fullWidth: 2182,
                    fullHeight: 1937,
                    aspectRatio: undefined
                  }}
                />
              </AntdPopover>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "columns",
    "multilimpador",
    "descricaoMulti",
    "porcelato",
    "descricaoMulti2",
    "porcelatoPesada",
    "descricaoMulti3"
  ],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  columns: [
    "columns",
    "multilimpador",
    "descricaoMulti",
    "porcelato",
    "descricaoMulti2",
    "porcelatoPesada",
    "descricaoMulti3"
  ],
  multilimpador: ["multilimpador", "descricaoMulti"],
  descricaoMulti: ["descricaoMulti"],
  porcelato: ["porcelato", "descricaoMulti2"],
  descricaoMulti2: ["descricaoMulti2"],
  porcelatoPesada: ["porcelatoPesada", "descricaoMulti3"],
  descricaoMulti3: ["descricaoMulti3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageBanerSection: "div";
  h1: "h1";
  columns: "div";
  multilimpador: typeof AntdPopover;
  descricaoMulti: "div";
  porcelato: typeof AntdPopover;
  descricaoMulti2: "div";
  porcelatoPesada: typeof AntdPopover;
  descricaoMulti3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicServices__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicServices__VariantsArgs;
    args?: PlasmicServices__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicServices__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicServices__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    columns: makeNodeComponent("columns"),
    multilimpador: makeNodeComponent("multilimpador"),
    descricaoMulti: makeNodeComponent("descricaoMulti"),
    porcelato: makeNodeComponent("porcelato"),
    descricaoMulti2: makeNodeComponent("descricaoMulti2"),
    porcelatoPesada: makeNodeComponent("porcelatoPesada"),
    descricaoMulti3: makeNodeComponent("descricaoMulti3"),

    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
