/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1XWyRcacryEyco6uPV1CR
// Component: acIxLOLj6-zV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: lKu0B9xgLMgZ/component
import CaseStudiesWraper from "../../CaseStudiesWraper"; // plasmic-import: sQiQl3EHt-JM/component
import Button from "../../Button"; // plasmic-import: vFerdvZMwcM9/component
import CtaBottom from "../../CtaBottom"; // plasmic-import: Su-8_eq-d-9U/component
import Footer from "../../Footer"; // plasmic-import: U1-LJF1kZHcJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: m1XWyRcacryEyco6uPV1CR/projectcss
import sty from "./PlasmicStories.module.css"; // plasmic-import: acIxLOLj6-zV/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 57zAO7P9sacL/icon

createPlasmicElementProxy;

export type PlasmicStories__VariantMembers = {};
export type PlasmicStories__VariantsArgs = {};
type VariantPropType = keyof PlasmicStories__VariantsArgs;
export const PlasmicStories__VariantProps = new Array<VariantPropType>();

export type PlasmicStories__ArgsType = {};
type ArgPropType = keyof PlasmicStories__ArgsType;
export const PlasmicStories__ArgProps = new Array<ArgPropType>();

export type PlasmicStories__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  pageBanerSection?: Flex__<"div">;
  h1?: Flex__<"h1">;
  section?: Flex__<"section">;
  columns?: Flex__<"div">;
  ctaBottom?: Flex__<typeof CtaBottom>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultStoriesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStories__RenderFunc(props: {
  variants: PlasmicStories__VariantsArgs;
  args: PlasmicStories__ArgsType;
  overrides: PlasmicStories__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__nMcDc)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Stories"}
              </h1>
            </div>
          </div>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__vOwj)}>
              <div className={classNames(projectcss.all, sty.freeBox__uIrQ)}>
                <div className={classNames(projectcss.all, sty.freeBox__gb43M)}>
                  <div
                    data-plasmic-name={"columns"}
                    data-plasmic-override={overrides.columns}
                    className={classNames(projectcss.all, sty.columns)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___8S1Bq)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__lRi0B
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__lSvtA)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__suVp
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__kwY4Q)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girls18285391920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qIKx7)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__eYIjX
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__l8XkT)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/woman32879561920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__s9R0U)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__uYWzO
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__lMzjf)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl18484541920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1279,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__r0Vpm)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__h4R6D
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__oHcI2)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl23664381920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__amdju)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__euOqi
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__nvKPn)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__jToId
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__ouzEq)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/woman31165871920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1279,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__nF6T)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__f7Pj7
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__jYzuU)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl17750351920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1191,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <CtaBottom
            data-plasmic-name={"ctaBottom"}
            data-plasmic-override={overrides.ctaBottom}
            className={classNames("__wab_instance", sty.ctaBottom)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "section",
    "columns",
    "ctaBottom",
    "footer"
  ],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section", "columns"],
  columns: ["columns"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageBanerSection: "div";
  h1: "h1";
  section: "section";
  columns: "div";
  ctaBottom: typeof CtaBottom;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStories__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStories__VariantsArgs;
    args?: PlasmicStories__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicStories__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicStories__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStories__ArgProps,
          internalVariantPropNames: PlasmicStories__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStories__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStories";
  } else {
    func.displayName = `PlasmicStories.${nodeName}`;
  }
  return func;
}

export const PlasmicStories = Object.assign(
  // Top-level PlasmicStories renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    columns: makeNodeComponent("columns"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicStories
    internalVariantProps: PlasmicStories__VariantProps,
    internalArgProps: PlasmicStories__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStories;
/* prettier-ignore-end */
