/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1XWyRcacryEyco6uPV1CR

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsqsCqaRxKnFa0 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qsCqaRxKNFa0/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsqsCqaRxKnFa0
});
